trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.0.x'
  displayName: 'Instalar .NET SDK'

- script: dotnet restore
  displayName: 'Restaurar dependencias'

# Preparar análisis SonarCloud
- task: SonarCloudPrepare@4
  inputs:
    SonarCloud: 'sonar_cloud_token'
    organization: 'alexiotovv'
    scannerMode: 'dotnet'
    projectKey: 'WebApi-CRUD'
    projectName: 'WebApi-CRUD'
  displayName: 'Preparar análisis SonarCloud'

# Compilar
- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Compilar proyecto'

# Analizar
- task: SonarCloudAnalyze@4
  displayName: 'Analizar código con SonarCloud'

# Publicar resultados
- task: SonarCloudPublish@4
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publicar resultados SonarCloud'

# Tests
- script: dotnet test --configuration $(buildConfiguration) --no-build
  displayName: 'Ejecutar pruebas unitarias'

# Artefactos
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'