trigger:
  - main # Se ejecuta al ahcer push en main

pool:
  vmImage: 'windows-latest' # Usamos windows para .NET

variables:
  buildConfiguration: 'Release'

stages:
- stage: BuildAndTest
  displayName: 'Compilación y Pruebas'
  jobs:
  - job: Build
    steps:
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.0.0'
        displayName: 'Instalar .NET SDK'
      - script: dotnet restore
        displayName: 'Restaurar dependencias'
      
      # Preparar análisis SonarQube/SonarCloud
      - task: SonarCloudPrepare@4
        inputs:
          SonarCloud: 'github.com_Alexiotovv'
          organization: 'alexiotovv'
          scannerMode: 'MSBuild'
          projectKey: 'WebApi-CRUD' # clave única del proyecto en SonarQube/SonarCloud
          projectName: 'WebApi-CRUD'

      # Compilar el proyecto
      - script: dotnet build --configuration $(buildConfiguration)
        displayName: 'Compilar proyecto'

      # Analizar código con SonarQube
      - task: SonarCloudAnalyze@4

      # Publicar resultados del análisis
      - task: SonarCloudPublish@4
        inputs:
          pollingTimeoutSec: '300'

      - script: dotnet test --configuration $(buildConfiguration) --no-build
        displayName: 'Ejecutar pruebas unitarias'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'