trigger:
  - main # Se ejecuta al ahcer push en main

pool:
  vmImage:'windows-latest' # Usamos windows para .NET

variables:
  buildConfiguration: 'Release'

stages:
- stage: BuildAndTest
  displayName: 'Compilación y Pruebas'
  jobs:
  - job: Build
    steps:
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.0.0'
        displayName: 'Instalar .NET SDK'
      - script: dotnet restore
        displayName: 'Restaurar dependencias'
      
      - script: dotnet build --configuration $(buildConfiguration)
        displayName: 'Compilar proyecto'

      - script: dotnet test --configuration $(buildConfiguration) --no-build
        displayName: 'Ejecutar pruebas unitarias'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'